apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}