# Default values for orders-extension.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gabbi/orders-extension
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.2"

service:
  type: ClusterIP
  port: 80

config:
  baseSite: electronics