apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: {{ include "order-created.fullname" . }}
spec:
  serviceBindingRef:
    name: {{ .Values.global.functions.orderCreated.bindings.occ.ref }}
  usedBy:
    kind: serverless-function
    name: {{ include "order-created.fullname" . }}
status: {}