apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "get-orders.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    path: /.*
  service:
    host: get-orders-{{ .Release.Namespace }}
    name: {{ include "get-orders.fullname" . }}
    port: 80
status: {}