apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders-extension.fullname" . }}
  labels:
    {{- include "orders-extension.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orders-extension.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orders-extension.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: GATEWAY_URL
            value: $({{ .Values.global.extensions.ordersExtension.bindings.occ.gatewayUrlVarName }})
          - name: BASE_SITE
            value: {{ .Values.config.baseSite }}
