# This is a basic workflow to help you get started with Actions

name: build-and-test-functions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - "functions/**"
  push:
    branches: [ main ]
    paths:
      - "functions/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-functions:
    defaults:
      run:
        working-directory: functions
    name: Test the Event triggers on node 12
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm test-with-coverage
        run: |
          npm install
          BASE_SITE=electronics GATEWAY_URL=https://mock.commerce.gateway npm run test-with-coverage
      - uses: codecov/codecov-action@v1.1.1
        if: github.ref == 'refs/heads/main'
        with:
          name: My Kyma Functions Code Coverage
          directory: functions/coverage
      - uses: romeovs/lcov-reporter-action@v0.2.16
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
